### ISSUE TITLE
Fix button alignment, find a solution to the absolute positioning

### ISSUE THREAD

**Issue by FinalAngel** [divio/djangocms-admin-style#13]
see: https://github.com/divio/django-cms/issues/3004

**Comment by diramazioni** [comment]
I was trying to fix it using extrastyle template override without success then I've realized that there is a mistake in admin/base_site.html in the order of evaluation and extrastyle doesn't override djangocms-admin.css and should be declared after. 
Just switch the two lines and add this extrastyle and the button it's finally aligned!
    {% block extrastyle %}
    .change-list #content-main .object-tools {
        float: right;
        margin-top: 5px;    
        z-index: 1;
    }
    </style>
    {% endblock %}

**Comment by FinalAngel** [comment]
thanks @diramazioni hope we can soon implement it :) If you'd like you could also open a Pull Request

**Comment by lory87** [comment]
@diramazioni the button alignment is fixed and will be updated in the new release
