### ISSUE TITLE
CMS pages list: wrong retina icon size

### ISSUE THREAD

**Issue by randomknowledge** [divio/djangocms-admin-style#210]
/static/admin/img/icon-no.gif and /static/admin/img/icon-yes.gif are not scaled down to 16px:

![screenshot](https://cloud.githubusercontent.com/assets/152249/10937380/b56f7572-82f2-11e5-98b1-43eaa58f4997.png)

**Comment by FinalAngel** [comment]
fixed in https://github.com/divio/djangocms-admin-style/pull/214 will be in 1.0.2
