### ISSUE TITLE
Strange styles in plugin editor

### ISSUE THREAD

**Issue by randomknowledge** [divio/djangocms-admin-style#211]
Hi there!

I see some strange stylings in the plugin editor.
First I don't like the table titles to be uppercased, but that's a matter of opinion of course.

Other than that - can you have a look at the icons near "SlideshowImage object"?
What's the "edit pen" icon for? It's not clickable.

Last point: Too me, nofile_48x48.png (image symbol with questionmark) looks like an error - wouldn't the icon work without the questionmark?

Thanks!
Florian

![plugin editor](https://cloud.githubusercontent.com/assets/152249/10937509/84b236da-82f3-11e5-830c-a17840c60aea.jpg)

**Comment by lory87** [comment]
Hi @randomknowledge 

Firstly which plugin do you exactly use?

The icon with questionmark is a placeholder if there is no file uploaded. We won't change the icon and the table title styles as well.

Thank you for your feedback.

Regards, Loriana

**Comment by randomknowledge** [comment]
Hi @lory87,

I use a custom plugin with a TabularInline. The image field is a FilerImageField.
I totally understand that you won't change the icon and the table titles, but can you explain to me what the pen icon is for?

Thanks in advance!
Florian

**Comment by lory87** [comment]
@randomknowledge checking and will give you feedback.

**Comment by lory87** [comment]
@randomknowledge I removed the widget icons on file and image fields because they are not necessary. You can change the image by clicking again to the magnifier. Will be changed in the next release. Thank you for your feedback.

**Comment by randomknowledge** [comment]
Thank you @lory87!
