### ISSUE TITLE
Admin header display: none;?

### ISSUE THREAD

**Issue by jsma** [divio/djangocms-admin-style#221]
Just installed 1.0.4 and now have a blank header in the admin. Browser inspection says djangocms-admin.css is `display: none;`-ing both the `#user-tools` and `#header #branding h1`.

<img width="1299" alt="screen shot 2015-11-05 at 2 40 55 pm" src="https://cloud.githubusercontent.com/assets/24574/10984007/3e8f75e0-83cb-11e5-8d2e-c3f294705515.png">

**Comment by lory87** [comment]
@jsma which cms version do you have installed?

**Comment by jsma** [comment]
Ah, that's it. Perhaps a backwards incompatible notice in the CHANGELOG then? Thanks!

**Comment by FinalAngel** [comment]
@lory87 can you adapt the changelog to include this specifically?

**Comment by lory87** [comment]
@FinalAngel I am already on it.

**Comment by lory87** [comment]
@jsma Notice is added to the CHANGELOG and will be on the next release
