### ISSUE TITLE
Top right button requires site to be an attribute of request object

### ISSUE THREAD

**Issue by itbabu** [divio/djangocms-admin-style#222]
Hi, 
I'm looking at the new admin interface. Nice work btw.

The top right button "Open *website name*" requires ```site```  to be an attribute of request object.
I couldn't find any reference in the documentation.
This can be achieved with [```django.contrib.sites.middleware.CurrentSiteMiddleware``` ](https://docs.djangoproject.com/en/1.8/ref/middleware/#django.contrib.sites.middleware.CurrentSiteMiddleware).
The only concern is that the middleware was added to Django 1.7, but Django-CMS 3.2 still supports Django 1.6.

**Comment by FinalAngel** [comment]
This is correct, @lory87 we might want to change ``{{ site_header|default:_('example.com') }}`` to ``{{ site_header|default:_('my site') }}``

**Comment by lory87** [comment]
@itbabu Thank you. Changed default text and will be fixed on next release
