### ISSUE TITLE
The `filter_vertical` setting is broken. It is horizontal, instead.

### ISSUE THREAD

**Issue by mfcovington** [divio/djangocms-admin-style#223]
I'm upgrading from `djangocms-admin-style==0.2.5` and noticed that the admin's [`filter_vertical`](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.filter_vertical) setting for many-to-many fields is no longer respected.

A vertical filter is actually horizontal in `djangocms-admin-style==1.0.4`:

<img width="966" alt="screen shot 2015-11-08 at 1 23 58 pm" src="https://cloud.githubusercontent.com/assets/1494842/11022765/2be6e1d2-861c-11e5-946a-fe3c880ac72d.png">

Also, vanilla Django admin and the older django CMS admin kept the filter box sizes consistent. It seems weird having them lopsided like this.

**Comment by mfcovington** [comment]
In the model admin:

```python
    filter_vertical = ['publications']
```

**Comment by mfcovington** [comment]
As you can see, there is also a `10em` margin on the top of `.selector ul.selector-chooser` which causes the second selector button to be invisible (in Safari on OS X). If I zoom out far enough, the other button comes into view, but the buttons are side-by-side when I think they are intended to be on top of one another:

<img width="960" alt="screen shot 2015-11-08 at 1 36 44 pm" src="https://cloud.githubusercontent.com/assets/1494842/11022828/e036ef82-861d-11e5-95ea-dfd9c896da5e.png">


In Chrome on OS X, the buttons are better, but the sizes of the boxes are still inconsistent with one another and the styling of the list within the selector box are very inconsistent between browsers. The vertical filter is also broken in Chrome:

<img width="957" alt="screen shot 2015-11-08 at 1 32 14 pm" src="https://cloud.githubusercontent.com/assets/1494842/11022813/74871e42-861d-11e5-8b8d-34578e2571bd.png">

**Comment by mfcovington** [comment]
Switching it to `filter_horizontal` brings back the missing button in Safari and the buttons are stacked as expected; however the box sizes are still lopsided and the buttons are pushed down by that top margin and look out of place:

<img width="947" alt="screen shot 2015-11-08 at 1 43 55 pm" src="https://cloud.githubusercontent.com/assets/1494842/11022868/293ec762-861f-11e5-9e09-6667464d84ea.png">

Interestingly, I see that there are 'Choose all'/'Remove all' options when using the horizontal filter. These are absent with the broken vertical filter for both Safari and Chrome.

**Comment by FinalAngel** [comment]
@mfcovington thank you very much for the extensive testing and feedback, we'll have a look at it today

**Comment by mfcovington** [comment]
@FinalAngel @lory87 Thank you! Please let me know if you need anything else.

**Comment by lory87** [comment]
@mfcovington Fixed this issue and will be changed in the next release.
