### ISSUE TITLE
inline admin UI is broken

### ISSUE THREAD

**Issue by chhantyal** [divio/djangocms-admin-style#234]
![screen shot 2015-11-12 at 15 47 17](https://cloud.githubusercontent.com/assets/862941/11121209/d1264864-8954-11e5-8dd3-df32157fdba2.png)

On above screenshot, first field is search field on foreignkey relation

**Comment by lory87** [comment]
@chhantyal which plugin are you using?

**Comment by chhantyal** [comment]
Hi @lory87 Not sure if I got your question. I don't use any plugin.

The above admin is default django inline admin https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.TabularInline

**Comment by lory87** [comment]
@chhantyal the issue is fixed and merged to develop. Will be in the next release.

**Comment by chhantyal** [comment]
Thank you :+1:
