### ISSUE TITLE
Re-enabling source maps without worrying about .css file sizes

### ISSUE THREAD

**Issue by mfcovington** [divio/djangocms-admin-style#250]
I noticed that source map creation has been disabled in `gruntfile.js` due to file size concerns:

    // Sourcemaps are disabled by default to reduce filesize
    // .pipe(sourcemaps.init())
        ...
    // Sourcemaps are disabled by default to reduce filesize
    // .pipe(sourcemaps.write())

Using `sourcemaps.write()` without an argument creates inline source maps within the destination `.css` files, thereby inflating those files; however, `sourcemaps.write('.')` will create external source maps at the same level as the destination `.css` files and leave the those `.css` files alone.

It seems that [external source maps are only loaded if developer tools are opened](http://stackoverflow.com/a/30777461/996114), so you can have source maps without worrying about the source map file sizes.

**Comment by FinalAngel** [comment]
@mfcovington thanks for the hint. We might actually want to port the implementation from django-cms: https://github.com/divio/django-cms/blob/develop/gulpfile.js#L96 where, when provided with the ``--debug`` flag, the sourcemaps get generated. We probably do not want to ship a release with sourcemap or debug information.

**Comment by lory87** [comment]
@mfcovington I implemented the debug option and merged to master. Changes will be on the next release.
