### ISSUE TITLE
Problems upload images

### ISSUE THREAD

**Issue by nilssolanki** [divio/djangocms-admin-style#258]
With djangocms-admin-style, when I open the image upload dialog, the two buttons at the top are not visible anymore (and few more other visual quirks). This is happening in version 1.0.4 and 1.0.6 in django-cms 3.1.3.

<img width="912" alt="bildschirmfoto 2015-11-20 um 15 27 02" src="https://cloud.githubusercontent.com/assets/5477955/11302120/c362dc7c-8f9b-11e5-878a-aa8f804c4f86.png">

**Comment by lory87** [comment]
@nilssolanki do you have current django-filer version?
Checking and give you feedback. Will reproduce the bug with your using versions.

**Comment by nilssolanki** [comment]
Thank you for your quick response. The django-filer is version is 0.9.12.

**Comment by lory87** [comment]
@nilssolanki could you please upgrade to 1.0.2 because there were some template changes which are necessary for the new django admin styles
