### ISSUE TITLE
admin filters is not usable when there is a lot of variants

### ISSUE THREAD

**Issue by vapask** [divio/djangocms-admin-style#260]
For example if there is filter by FK to model with on hundred or more elements

**Comment by lory87** [comment]
Hi @vapask 
Can you please provide us an example or any screenshots that we could easier reproduce the problem?
Thank you.

**Comment by vapask** [comment]
there are too many options on the page:
![example](https://cloud.githubusercontent.com/assets/797930/11420517/9b32ea1e-943f-11e5-8fff-513315766494.png)

I think it should be possible to collapse this block

**Comment by FinalAngel** [comment]
@vapask isn't that the normal behaviour of the Django admin in general when defining that many filters?

**Comment by vapask** [comment]
@FinalAngel Ok, my bad, I forgot about django default behaviour. I've just moved project from cms 2.4 with suit to 3.2 with admin-styles. Nevertheless there is beautiful solution of this problem in django-suit(dropdowns): 
![5bd7502364](https://cloud.githubusercontent.com/assets/797930/11421523/8076b6f4-9446-11e5-8e96-44fbb5a557aa.jpg)

**Comment by FinalAngel** [comment]
@vapask no problem, absolutely not your fault! Our efforts in djangocms-admin-style go as far as adapting the css. We do not want to touch the django default templates. However we could probably add scrolling on large filters using ``max-height`` eventually. Is that something you can digg into @lory87 ?

**Comment by lory87** [comment]
@FinalAngel and @vapask I'm going to add a max height. Will inform you when it's done.

**Comment by lory87** [comment]
@vapask I added a max height. The change will be in the next release.

**Comment by vapask** [comment]
@lory87 thank you very much
