### ISSUE TITLE
Translation for  {% trans 'Open' %} in 'djangocms_admin_style/templates/admin/inc/branding.html'

### ISSUE THREAD

**Issue by treavis** [divio/djangocms-admin-style#264]
There is no translation for {% trans 'Open' %} in Transifex - Django - admin project.
From 'djangocms_admin_style/templates/admin/inc/branding.html' - line 27

**Comment by treavis** [comment]
also {{ request.site.name|default:_('my site') }}

**Comment by FinalAngel** [comment]
Has been fixed in https://github.com/divio/djangocms-admin-style/pull/266

@mkoistinen can you confirm and close?

**Comment by treavis** [comment]
:+1:
