### ISSUE TITLE
id_username has no background color

### ISSUE THREAD

**Issue by sedrubal** [divio/djangocms-admin-style#268]
I have a dark system theme and so all text boxes in websites are dark too. As `#id_username` on the login page has no style (or at least no background colour) the text is black on dark, as you can see in the screenshot:

![djangocms_login](https://cloud.githubusercontent.com/assets/5571650/11595200/82f6d5ee-9aae-11e5-93d7-713adc92c809.png)

**Comment by lory87** [comment]
@sedrubal form fields are reseted and will be on next release.

**Comment by sedrubal** [comment]
:+1: great. Do you reset all form fields or just the login forms?

**Comment by lory87** [comment]
@sedrubal all fields. Please let me know if there is something missing.

**Comment by sedrubal** [comment]
Ah thank you @lory87 . Now I saw the commits... I'll report back, if I find something missing... Thx.
