### ISSUE TITLE
List display issues if no admin actions

### ISSUE THREAD

**Issue by jsma** [divio/djangocms-admin-style#275]
Here is what the display looks like with admin actions enabled:

![screen shot 2015-12-09 at 6 30 05 pm](https://cloud.githubusercontent.com/assets/24574/11705686/978b7c48-9ea6-11e5-8b3d-a52ab2219910.png)

Here's what it looks like with `actions = None`:

![screen shot 2015-12-09 at 6 30 26 pm](https://cloud.githubusercontent.com/assets/24574/11705691/a35b20e6-9ea6-11e5-8f47-52f162c383ae.png)

These screenshots are from 1.0.7 but I also tested this on master @121a91d97c8fa0fa953c35274b44d976a6a5e50a

**Comment by FinalAngel** [comment]
@jsma thanks for the report, will have a look at it :)

**Comment by lory87** [comment]
Hi @jsma 
I fixed the issue if no actions are visible and it will be in the next release.
