### ISSUE TITLE
Filer clear icon too big

### ISSUE THREAD

**Issue by jakob-o** [divio/djangocms-admin-style#277]
EDIT: My proposed solution does not work, the "nofile" image / icon is too big then.

Hey,

I am having trouble with the clear icon size of the filer image. When removing the image size it looks good, but I am not sure if this is the correct way to fix it.

Thank you in advance

Jakob

Versions
```
django-cms==3.2.0
djangocms-admin-style==1.0.7
django-filer==1.0.2
```

Screenshots

![filer_problem_01](https://cloud.githubusercontent.com/assets/1359384/11899176/9571ff74-a59d-11e5-9485-d8a89b51675c.png)

![filer_problem_02](https://cloud.githubusercontent.com/assets/1359384/11899189/a008c3fa-a59d-11e5-8f42-c029026ef489.png)

**Comment by lory87** [comment]
Hi @jakob-o

This issue is already fixed but not released yet. You will find the changes on master.
https://github.com/divio/djangocms-admin-style/blob/master/CHANGELOG.rst

**Comment by jakob-o** [comment]
Hi @lory87 ,
and thank you very much. Do you have an estimation when the next release is scheduled? As far as I can see there are no open issues anymore.

Regards

Jakob

**Comment by lory87** [comment]
Hi @jakob-o 

There will be a new release in the next days.

Regards, Lory
