### ISSUE TITLE
Djangocms Admin Style search box CSS broken with Django 1.9 and djangocms-admin-style==1.0.9

### ISSUE THREAD

**Issue by JoeJasinski** [divio/djangocms-admin-style#296]
Hi all, 

I recently upgraded to Django 1.9 and DjangoCMS 3.2.1.  I also updated djangocms-admin-style to the latest current version, 1.0.9.  Upon doing so, the search bar in the admin interface breaks for all instances where search_fields is set in the ModelAdmin.  I'm not able to click on the search box to make it active, and it appears broken in the layout.   I have reproduced this in Firefox (44.0) and in Chrome (50.0.2633.3)

See the screenshot below.  

I've run a collectstatic and have migrated everything upon doing this upgrade.  Here are the apps that I have installed. 

    $ pip freeze
    beautifulsoup4==4.4.0
    dj-database-url==0.3.0 
    Django==1.9.1
    django-classy-tags==0.6.2
    django-cms==3.2.1
    django-extensions==1.6.1
    django-formtools==1.0
    django-htmlmin==0.9.0
    django-nocaptcha-recaptcha==0.0.18
    django-reversion==1.10.1
    django-sekizai==0.9.0
    Django-Select2==4.3.1
    django-treebeard==4.0
    djangocms-admin-style==1.0.9
    djangocms-inherit==0.1.1
    djangocms-link==1.7.1
    djangocms-snippet==1.7.1
    djangocms-teaser==0.2.0
    djangocms-text-ckeditor==2.8.1
    html5lib==0.999999
    Pillow==3.1.0
    psycopg2==2.6.1
    six==1.9.0
    sorl-thumbnail==12.3
    wheel==0.24.0

![djangocms-admin-style-broken](https://cloud.githubusercontent.com/assets/417872/12711871/00755970-c889-11e5-948e-60b938d491df.jpg)

**Comment by FinalAngel** [comment]
Hello @JoeJasinski, thanks for the report. We have already addressed the issues related to Django 1.9 (https://github.com/divio/djangocms-admin-style/blob/master/CHANGELOG.rst#110-unreleased) and will release them shortly (today).

**Comment by FinalAngel** [comment]
Has been released just now :)

**Comment by imagescape** [comment]
Awesome, thank you!

**Comment by JoeJasinski** [comment]
Thank you!
