### ISSUE TITLE
horizontal fields in site admin

### ISSUE THREAD

**Issue by jbazik** [divio/djangocms-admin-style#298]
In an app that coexists with django-cms on my site, the admin declares:

 fieldsets = (
        (None, {
            'fields': (('shortname', 'published', 'notfeature'),),
        }),
...

I get
![got](https://cloud.githubusercontent.com/assets/533519/12832481/469fca8e-cb68-11e5-822b-24794a1d4c05.png)

I want
![want](https://cloud.githubusercontent.com/assets/533519/12832490/53fa93bc-cb68-11e5-9cce-aa99e3d336bd.png)

Looks to me like djangocms-admin-style sets float to none and removes horizontal margins:

form .form-row .field-box {
    float: none;
    margin-right: 0 !important;
    margin-top: 20px;
}

Am I doing something wrong?  Without djangocms-admin-style, the admin form looks right, but I'm also using django-cms, and it's a requirement.

**Comment by FinalAngel** [comment]
@jbazik thanks for your report. This looks in general good to me as we changed all forms in djangocms-admin-style to be underneath. This would also be the standard case for mobile.

**Comment by jbazik** [comment]
Well, no, I don't agree.  When I write a django app, I have the option to make my admin forms more compact by grouping fields so they are presented horizontally:

https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fields

It's possible to restyle the admin without taking away this option.  It does not affect rendering on mobile devices because a float will wrap if there is not enough space for it.  I want to have some control over how my options are presented to my users to make their lives easier.  And djangocms-admin-style affects all apps, not just django-cms.

I like very much the work you've done.  I prefer this styling to the default.  Is there a reason you can't restore this option?

**Comment by FinalAngel** [comment]
@jbazik we would have to have a closer look. Though cannot promise you to fix this in the coming weeks. I'll add it to our backlog.

**Comment by vivazzi** [comment]
I'm agree with @jbazik . djangocms-admin-style break django horizontally view. Horizontally view is more comfortable in many cases. For example:
Big:
![long](https://cloud.githubusercontent.com/assets/11954799/13164714/0dd19c68-d6ea-11e5-86e9-16134f9d0337.png)

Compact:
![short](https://cloud.githubusercontent.com/assets/11954799/13164619/405cb18c-d6e9-11e5-8e55-a87e7aff41e5.png)

As solve, I can suggest to try add media rule in css for mobile view.

And djangocms-admin-style is beatutiful style for admin. I use only it for my projects! Thanks.

**Comment by Treverix** [comment]
I vote for horizontal alignment too.


This is how our admin looks like after the upgrade of djangocms-admin-style:
![image](https://cloud.githubusercontent.com/assets/1685275/13179650/1a2b91a4-d725-11e5-86c7-13ee02e27670.png)

And this is how it looked before.
![image](https://cloud.githubusercontent.com/assets/1685275/13179734/82eeb234-d725-11e5-8fed-5248a74e099b.png)

Now we have to downgrade to 0.2.5, unfortunately.

**Comment by vivazzi** [comment]
@Treverix you can add some fixes to not downgrade:
```
# your theming.css

form .form-row .field-box {float: left;margin-top: 0;margin-right: 20px!important;}
```

**Comment by Treverix** [comment]
@vivazzi it doesn't work at all. Played with your suggestion - based on V1.1.0 - and label, input field and buttons are always on three lines. There is no class '.field-box', but I guess this is the class for attribute fictional 'box' and I replace it so that it matches real attributes, right?

**Comment by vivazzi** [comment]
@Treverix my suggestion works for me in the following way:
1 - Put base.html to your spicific app for example:
```
# specific_app/templates/admin/base.html
{% extends "admin:admin/base.html" %}
{% load sb_tags %}
{% block blockbots %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}specific_app/css/theming.css" />
{% endblock %}
```
* the adding of css file to block blockbots as variant 

2 - Add your specific app to INSTALLED_APPS before 'djangocms_admin_style'
```
INSTALLED_APPS = (
    ...
    'specific_app',
    'djangocms_admin_style',
    'django.contrib.admin',
    ...
)
```
3 - Create your theming.css:
```
form .form-row .field-box {float: left;margin-top: 0;margin-right: 20px!important;}
```

**Comment by Treverix** [comment]
Sorry, should have explained more precisely: I've add your suggested css styles with google devTools directly on the div with classes 'form-row form-myfield' (form-box in your example) and made sure, the 3 styles are active (not overriden by some !important styles). And that changed nothing on the layout.
Tried this with version 1.10 of admin style.

I was able to save some other problems, though. One was related to bootstrap. The old style was compatible with bootstrap (to some extend) but I had to remove it now. It broke too much.

Another problem is that the new styles uses a lot of !important styles on ul and li elements which is causes a lot of problems with the chose widgets as replacement for selects.

**Comment by lory87** [comment]
@jbazik, @Treverix, @vivazzi We are working on this issue and will let you know when we are going to release some changes

**Comment by tom-mi** [comment]
+1 for a style closer to the original django admin. Just compare this
![django_admin_broken](https://cloud.githubusercontent.com/assets/3297149/13550400/2f4ee64a-e31d-11e5-803e-846e13d6dd5a.png)
to the clarity and compactness of the original django admin gui:
![django_admin](https://cloud.githubusercontent.com/assets/3297149/13550410/8fe53e82-e31d-11e5-8b73-6b7c8e19785c.png)
IMHO the extra buttons which are part of the date or dropdown field (from a user's perspective) are supposed to be in the same line as the respective field.

**Comment by lory87** [comment]
@jbazik, @Treverix, @vivazzi and @tom-mi We changed the width of the form fields back that they are not anymore full-width if they are grouped. The changes are merged to master branch.

Thank you for your feedback.

**Comment by vstoykov** [comment]
@lory87 I tested master branch and when I group fields in admin like that:

    fields = [
        ('field1', 'field2'),
        'field3,
    ]

everything works as in vanilla django, but what about datetime fields as shown by @Treverix, or even the screenshot shown by @tom-mi ?

Probably this is different issue from the initially reported by @jbazik but split fields (like datetime field) and all additional buttons (for adding, editing, or selecting date) preferably should be at the same row as the field itself.

**Comment by lory87** [comment]
@vstoykov thank you for your feedback. I changed position of date and calendar pickers and of additional buttons (edit, add) too. Changes are on master and will be in next release.
