### ISSUE TITLE
Big margin top between many to many horizontal view in mobile

### ISSUE THREAD

**Issue by vivazzi** [divio/djangocms-admin-style#299]
![margin](https://cloud.githubusercontent.com/assets/11954799/13164857/f444e754-d6ea-11e5-8d97-f57d6039c96a.png)

As solve, add:
```
@media only screen and (max-width: 768px), print {
    .selector ul.selector-chooser {margin: 0!important;}
}
```

**Comment by lory87** [comment]
@vivazzi This issue is fixed, merged to master and will be in the next release
