### ISSUE TITLE
Add ability to make dropdown filter menu

### ISSUE THREAD

**Issue by vivazzi** [divio/djangocms-admin-style#300]
I think, good idea is to have option to make dropdown filter menu as django-cms page list:
![default](https://cloud.githubusercontent.com/assets/11954799/13165858/21299efa-d6f4-11e5-817d-8d8545c16aa5.png)

Option may be like that:
```
@admin.register(Example)
class ExampleAdmin(DjangocmsAdminStyleMix, admin.ModelAdmin):
    ...
    dropdown_filter_list = True
```

**Comment by lory87** [comment]
@vivazzi we will have a look and will let you know if there are some changes.

**Comment by mikek** [comment]
@vivazzi, It is not completely clear what feature do you want to be implemented in this application. Can you, please provide an example?
We are revisiting the filter and search functionality in 3.3 to make it more user friendly, though. So you might be interested in those changes in the [django CMS repository](https://github.com/divio/django-cms) itself.

**Comment by lory87** [comment]
gentle ping @vivazzi. Can you provide us an example? Or is the Issue fixed in 3.3 (django CMS repository). Thank you for your feedback in advance.

**Comment by vivazzi** [comment]
@mikek, @lory87 I suggest add dropdown filter as django cms has for structure of page list. I try to describe my suggestion in pictures.
Now:
![before](https://cloud.githubusercontent.com/assets/11954799/14486177/2fe80070-018e-11e6-9618-83fcd77dbb79.png)
That is I suggest:
![after](https://cloud.githubusercontent.com/assets/11954799/14486194/3b9434c0-018e-11e6-9928-c9591e6e7781.png)
In other words: filter menu override content behind (we can click for dropdown). It helps us save place on mobile devices as it added for django cms:
![ex](https://cloud.githubusercontent.com/assets/11954799/14486402/22eaeff8-018f-11e6-85a5-ed348b1590aa.png)

I hope my suggestion is clear

**Comment by FinalAngel** [comment]
@vivazzi the filter will be changed in django CMS to be implemented via the search element for the page tree: https://github.com/divio/django-cms/pull/5134

However, we cannot add an option to make the filter menu hovering over the content. This is Django default behaviour and probably needs a proposal on the Django Admin itself. djangocms-admin-style is only overriding styles and not providing additional settings.

You have the option to overwrite the filter template yourself and add the corresponding css in:
https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/filter.html
