### ISSUE TITLE
Input line height issue in linux

### ISSUE THREAD

**Issue by radiac** [divio/djangocms-admin-style#303]
Under certain conditions (eg Ubuntu using fallback font Verdana), the line height (12px) for input and select elements can be too low for the font size (12px), causing descenders and underscores to be cropped by the padding:

![example](https://cloud.githubusercontent.com/assets/241712/13455090/36b4d240-e053-11e5-9c51-47a68e5205fa.png)

120% line height should resolve this, which would be 14.4px, so I tried increasing the line height to large font size (16px) and reducing the vertical padding accordingly, but it caused problems in IE. This will therefore either need further css hackery to fix those issues, or it becomes a design decision around input element sizes and padding.

**Comment by lory87** [comment]
@radiac this issue is fixed and merged to master. Change will be in next release
