### ISSUE TITLE
cleanup static file locations

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-admin-style#305]
static files should be all namespaced inside a app folder inside ``static``. Anything placed directly in ``static`` might clash with other static assets of the project.

So all djangocms-admin-style staticfiles should be in ``static/djangocms_admin_style/``. Of course with the exception of static files that are overridden for other apps.

- [ ] [``static/js``](https://github.com/divio/djangocms-admin-style/tree/49301e0af6ed719ce9be86747df7504c4df324ef/djangocms_admin_style/static/js) should be in [``static/djangocms_admin_style/js/``](https://github.com/divio/djangocms-admin-style/tree/49301e0af6ed719ce9be86747df7504c4df324ef/djangocms_admin_style/static/djangocms_admin_style/).
- [ ] once django-filer 1.2.0 is released, ``static/icons`` and ``static/filer/icons`` can be removed

**Comment by lory87** [comment]
@stefanfoulis filer icons are removed and js moved to static/djangocms_admin_style
