### ISSUE TITLE
ability to change a user's password

### ISSUE THREAD

**Issue by miraculixx** [divio/djangocms-admin-style#308]
currently it appears that a user's password is displayed without a possibility to change it (no link to the password change page as in the standard admin). Is there some option to enable this?

**Comment by FinalAngel** [comment]
+1 @lory87 can we add this entry to the "Django administration" dropdown?

**Comment by lory87** [comment]
@FinalAngel yes sure will inform you @miraculixx when it is added to the dropdown.

**Comment by FinalAngel** [comment]
@miraculixx this should already be the case:
![image](https://cloud.githubusercontent.com/assets/270307/14199257/15525d46-f7e3-11e5-98fb-efe7b52a94ca.png)

/cc @lory87

**Comment by miraculixx** [comment]
@FinalAngel I meant this link for an admin to change _any_ user's password:

![image](https://cloud.githubusercontent.com/assets/859611/14202050/1a3f0e90-f7f6-11e5-8316-427fea6e3ce3.png)

**Comment by FinalAngel** [comment]
@miraculixx this is still present in the current implementation, no change there:
![image](https://cloud.githubusercontent.com/assets/270307/14207196/da97983e-f818-11e5-9fb3-fdcb67d9e907.png)

**Comment by FinalAngel** [comment]
gentle ping @miraculixx is it the first or second case?

**Comment by miraculixx** [comment]
@FinalAngel thanks for the ping. I must have confused the two cases, as indeed as per your screenshot it works for the general admin - so indeed, I meant the second case. I'll consider opening an issue with CMS. Thanks for clearing things up.
