### ISSUE TITLE
static/filer/icons/file_32x32.png is replaced with a 64x64.png image

### ISSUE THREAD

**Issue by PamelaM** [divio/djangocms-admin-style#321]
When we include djangocms_admin_style and run collectstatic, the static/filer/icons/file_32x32.png is updated.  However, the icon that gets created is actually 64x64!  I'm not familiar enough with this project's setup/build process to identify where in the pipeline the incorrect image is being generated.

Also, why does djangocms_admin_style overwrite static/filer/icons at all?  Those icons are used outside of the admin.

**Comment by PamelaM** [comment]
It appears that this problem has been addressed in master.  I expect that this issue can be just closed or even deleted.

**Comment by FinalAngel** [comment]
Thanks @PamelaM for the report. Is it already fixed with 1.1.0 for you or just the latest master branch?

**Comment by lory87** [comment]
@PamelaM this issue is already fixed in master branch.

**Comment by PamelaM** [comment]
Any idea when 1.1.1 will be created and moved to pypi?

**Comment by lory87** [comment]
@PamelaM expected, we will do a release this week
