### ISSUE TITLE
Required field error style

### ISSUE THREAD

**Issue by vldy** [divio/djangocms-admin-style#330]
Can you make the massages for the errors more understandable. Right now it is a little confusing which field is required(top or bottom). 
![screenshot from 2016-04-22 14 50 01](https://cloud.githubusercontent.com/assets/6543184/14740909/23711d4a-089b-11e6-8dba-64b5fc6d4593.png)

Without django-admin-style:
![screenshot from 2016-04-22 15 00 19](https://cloud.githubusercontent.com/assets/6543184/14740908/23708c04-089b-11e6-9edb-b53be8e9477f.png)

**Comment by lory87** [comment]
@vldy thank you for your indication. We added an highlighted are. Changes are merged to master. Release will be coming soon.
