### ISSUE TITLE
Calendar next/previous links are invisible

### ISSUE THREAD

**Issue by jsma** [divio/djangocms-admin-style#349]
The shortcut links `<` and `>` on the calendar widget are invisible.

<img width="333" alt="screen shot 2016-06-16 at 5 04 07 pm" src="https://cloud.githubusercontent.com/assets/24574/16137026/699da65c-33e4-11e6-893b-654f3d20faed.png">

Technically, the top left and right corners of the widget are still clickable, but since the editors can't see them, they assume they don't exist, leading to frustration and confusion.

I've tested against both 1.2.2 and the most recent commit fa1838def and the problem exists in both versions. Also, I've confirmed that if I disable djangcms-admin-style, Django's default calendar widget does not have this issue.

**Comment by FinalAngel** [comment]
thank you for the report @jsma . Any chance you could create a PR to fix this?

**Comment by jsma** [comment]
Django's [widgets.css](https://github.com/django/django/blob/master/django/contrib/admin/static/admin/css/widgets.css#L476) applies `text-indent: -9999px;` to the prev/next links. If I disable this style in Chrome dev tools, the arrows reappear (but the alignment is off a bit). 

<img width="589" alt="screen shot 2016-06-17 at 11 45 29 am" src="https://cloud.githubusercontent.com/assets/24574/16161204/125933e6-3481-11e6-8992-548d7827037b.png">

I'm not sure what the root issue is though, since this CSS works just fine in the standard Django admin. Unfortunately, I'm not going to be able to get a quality PR together anytime soon.

**Comment by FinalAngel** [comment]
thank you @jsma we'll have a look then :)

**Comment by FinalAngel** [comment]
@jsma I just had a look and in latest master it looks correctly:

![image](https://cloud.githubusercontent.com/assets/270307/16195675/0406c48a-36fb-11e6-8e4f-c62f92735818.png)

Did you check it out with the latest master Version?

**Comment by jsma** [comment]
Yes, I just installed via `pip install git+https://github.com/divio/djangocms-admin-style.git` and the issue persists. I've also confirmed that my browser is loading the CSS from this install, and not any cached versions. I should also note I'm on Django==1.9.7.

**Comment by FinalAngel** [comment]
ah I haven't tried Django 1.9 yet, will do that then :) thanks @jsma

**Comment by FinalAngel** [comment]
Closed in the latest master @jsma thanks to @lory87 . Will be released this week :)
