### ISSUE TITLE
NoReverseMatch exception triggered on object deletion.

### ISSUE THREAD

**Issue by tvanesse** [divio/djangocms-admin-style#35]
Whenever you try to delete an object from the admin with Django 1.7 and Python 2.7, you end up with a `NoReverseMatch` exception raised in 

```
djangocms_admin_style/templates/admin/delete_selected_confirmation.html
```

The traceback says 

```
Reverse for 'app_list' with arguments '()' and keyword arguments '{u'app_label': ''}' not found.
```

and this is related to line 11 of the template which renders the nested menu (depicted below).
![screenshot from 2014-12-31 13 04 31](https://cloud.githubusercontent.com/assets/6845103/5587563/3ae9529c-90ee-11e4-83f9-bb5b04dafd5a.png)

I can provide a fix that was successfully tested under Django 1.7 and Python 2.7 in a pull request if one of the contributors agrees.

**Comment by acspike** [comment]
I'm also experiencing this problem. Could you share the fix?

**Comment by yakky** [comment]
This should already have been fixed in #23, available in current version 0.2.5

**Comment by yakky** [comment]
@acspike @tvanesse is this still the case using latest version?

**Comment by lory87** [comment]
@acspike @tvanesse This issue is fixed and will be updated in the new release
