### ISSUE TITLE
Regression in Stacked inline in djangocms-admin-style==1.2.3

### ISSUE THREAD

**Issue by vstoykov** [divio/djangocms-admin-style#355]
After upgrade to djangocms-admin-style==1.2.3 StackedInline is not full width anymore.

Before (1.2.2)

![djangocms-admin-style-before-regression-stackedinline](https://cloud.githubusercontent.com/assets/902381/16377855/19b802fa-3c71-11e6-9edd-2125bf402c47.png)

After (1.2.3)

![djangocms-adminstyle-regression-stackedinline](https://cloud.githubusercontent.com/assets/902381/16377858/1eb99e80-3c71-11e6-93f3-4ac6e410a87d.png)

**Comment by vstoykov** [comment]
I bisected the changes and found that the reason is in this commit https://github.com/divio/djangocms-admin-style/commit/a5a4b50770820ce78d12bc67c3fc3de0ca73cd43

Probably settings the width for particular case need to be done without `!important`

**Comment by lory87** [comment]
https://github.com/divio/djangocms-admin-style/pull/356

**Comment by lory87** [comment]
https://github.com/divio/djangocms-admin-style/issues/354

**Comment by lory87** [comment]
@vstoykov I merged the fixes to master.
