### ISSUE TITLE
Fix datetime fields when grouped inline

### ISSUE THREAD

**Issue by vstoykov** [divio/djangocms-admin-style#359]
When in admin you group fields like that:

    fields = (
        'field1',
        'field2',
        ('field3', 'field4'),
        'field5',
    )

Both `field3` and `field4` will be on the same row. The problem is when one of this fields is a datetime field because it is already split on two separate fields.

This is how it should look like:
![djangocms-admin-style-datetime-fixed](https://cloud.githubusercontent.com/assets/902381/16408875/67767fdc-3d23-11e6-9713-91947c5c1af5.png)

But now it looks like:
![djangocms-admin-style-datetime-broken](https://cloud.githubusercontent.com/assets/902381/16408892/892063c8-3d23-11e6-9c6c-d764e821234e.png)

Proposed solution:

    .form-row p.datetime .vDateField{
        width: calc(100% - 151px)!important;
    }
    .form-row p.datetime .vTimeField{
        width: calc(100% - 152px)!important;
    }

P.S. In the "How it should look like" i changed the styles for the select in order "delete" button to be on the same row: from `width: calc(100% - 91px)!important;` to `width: calc(100% - 132px)!important;`

**Comment by lory87** [comment]
@vstoykov Thank you for reporting this issue. It is because of missing label wrapper on date and time text. I'm checking to solve this issue otherwise and will let you know when changes are merged to master.

**Comment by lory87** [comment]
@vstoykov datetime fields are fixed and merged to master. I'm working now on fixes for related widget links.

**Comment by lory87** [comment]
@vstoykov issue about related widget wrapper links is fixed and merged to master. Thank you for your feedback and let us know if we can close this issue.

**Comment by vstoykov** [comment]
Thanks @lory87 it is fixed now.
