### ISSUE TITLE
select multiple overflowing on chrome on backend

### ISSUE THREAD

**Issue by jschneier** [divio/djangocms-admin-style#36]
I've got an m2m field in the admin that is overflowing the container on Chrome (works great on Firefox).

![screen shot 2015-01-13 at 4 59 15 pm](https://cloud.githubusercontent.com/assets/2245080/5730119/a9f33b92-9b45-11e4-983a-d2f8a5ff39b9.png)

I believe the issue is this line: https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/libs/html5-boilerplate/_styles.scss#L80

Maybe add a rule for ``select[multiple]``?? and do ``overflow: hidden`` or ``overflow: auto``. CSS in not my forté.

**Comment by yakky** [comment]
Please check PR #38

**Comment by jschneier** [comment]
Awesome!

**Comment by mfcovington** [comment]
@yakky Do we have an ETA for v0.2.6 or should I just install from GitHub to fix this issue on my site?

**Comment by yakky** [comment]
@mfcovington this weekend. Actually this just slipped by and I forgot to push a release :confused:

**Comment by mfcovington** [comment]
Awesome! Thanks.

**Comment by yakky** [comment]
Released!

**Comment by mfcovington** [comment]
@yakky I just installed 0.2.6; however, it looks to be the wrong version as it doesn't contain `form select[multiple] { overflow: auto; width: 100%;  max-width: 240px; }` on line 107 of `djangocms_admin_style/sass/partials/_forms.scss`

**Comment by yakky** [comment]
@mfcovington bummer. 0.2.7 is out which fixes this for real
