### ISSUE TITLE
pattern selector for hiding related widget links is insufficiently selective

### ISSUE THREAD

**Issue by jbazik** [divio/djangocms-admin-style#372]
In components/_forms.scss:

```
// styles should only grab if there is an image upload
// appears on form rows with file, image and visual in class name #242, #220
&[class*="file"],
&[class*="image"],
&[class*="visual"] {
    .related-widget-wrapper-link {
        // hides related widget wrapper links because they don't work correctly and are not necessary
        // because of magnifier and delete link #220
        display: none;
        width: 36px;
        height: 36px;
    }
```

That has the unintended effect of hiding related model links for **any** field that just happens to have any of those words ('file', 'image', 'visual') in its name.  For instance, I have a foreignkey field named "images" in one of my models, which django makes into:

`<div class="form-row field-images">`

The css rules above match, and I get no "add another" link.

**Comment by vxsx** [comment]
Should be fixed on latest master.
