### ISSUE TITLE
Inputs in admin.StackedInline have small widths

### ISSUE THREAD

**Issue by rafalp** [divio/djangocms-admin-style#389]
Text inputs become tiny when usimg StackedInline style for inline admin:

<img width="1068" alt="zrzut ekranu 2017-08-07 o 14 36 19" src="https://user-images.githubusercontent.com/750553/29026796-e49d648c-7b7d-11e7-8839-8c8d69c53a9a.png">

On sidenote, borders between inline forms in stacked inline should be visually more noticeable, like how default Django does them:

<img width="1388" alt="zrzut ekranu 2017-08-07 o 14 40 03" src="https://user-images.githubusercontent.com/750553/29026899-5bff43ba-7b7e-11e7-83cf-e043024433d6.png">

**Comment by rafalp** [comment]
Here's small experiment that IMHO greatly improves visual clarity of stacked inlines:

![zrzut ekranu 2017-08-07 o 15 00 42](https://user-images.githubusercontent.com/750553/29027534-5c713724-7b81-11e7-9a3c-85f313597943.png)

**Comment by FinalAngel** [comment]
@rafalp we would welcome a pull request :)

**Comment by rafalp** [comment]
I could try to cook the PR with styles change on the weekend, if I won't get distracted by something else ;)

**Comment by FinalAngel** [comment]
@rafalp that would be awesome 👍

**Comment by rafalp** [comment]
Closing this per PR merge, thanks!
