### ISSUE TITLE
Select box spills all of it's options all over the form

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-admin-style#39]
I've got a multiple select field with the max-width set at 240px and the overflow visible.

This is surely an issue as it constrains the select box and then spills out all of it's options in the form?!

![screen shot 2015-03-05 at 13 44 04](https://cloud.githubusercontent.com/assets/1461191/6505812/b0a7895a-c33d-11e4-9bd5-91d74f1b2899.png)

**Comment by yakky** [comment]
This should have been fixed in #38, still not release, though

**Comment by marksweb** [comment]
Ah right, I should really of checked the closed issues!

Well, I'll create some overriding stylesheets & keep an eye out for the next release.

**Comment by yakky** [comment]
no worries :) just as you are it, you can give master a try if it fixes the issue for you
