### ISSUE TITLE
wrong admin help-text margin

### ISSUE THREAD

**Issue by kinkerl** [divio/djangocms-admin-style#393]
The help-text `margin-left` in the admin on a new django-cms installation is moved 160px to the right. 
This is a change done between django 1.8 and 1.11 but it looks broken in the current with the djangocms-admin-styles.

![bug3](https://user-images.githubusercontent.com/71950/35967952-bd73020a-0cc2-11e8-92f4-397e95cd1fd2.png)

dj-database-url==0.4.2
Django==1.11.10
django-classy-tags==0.8.0
django-cms==3.5.0
django-filer==1.3.0
django-formtools==2.1
django-mptt==0.8.7
django-polymorphic==1.3
django-sekizai==0.10.0
django-treebeard==4.2.0
djangocms-admin-style==1.2.7
djangocms-attributes-field==0.3.0
djangocms-column==1.7.0
djangocms-file==2.0.2
djangocms-googlemap==1.1.1
djangocms-installer==1.0.0
djangocms-link==2.1.2
djangocms-picture==2.0.6
djangocms-snippet==2.0.0
djangocms-style==2.0.2
djangocms-text-ckeditor==3.5.3
djangocms-video==2.0.4
easy-thumbnails==2.5
html5lib==0.9999999
Pillow==5.0.0
pkg-resources==0.0.0
pytz==2017.3
six==1.11.0
tzlocal==1.5.1
Unidecode==0.4.21

**Comment by metaforx** [comment]
yes. indeed. realised this in some of our recent project implementations as well, will definitely be fixed.
