### ISSUE TITLE
admin.TabularInline, models.DateTimeField style problems

### ISSUE THREAD

**Issue by thelittlebug** [divio/djangocms-admin-style#408]
![image](https://user-images.githubusercontent.com/2874956/52008582-335cdf00-24d1-11e9-8111-dfa3f0a14fec.png)

am i doing something wrong? im using djangocms-admin-style-1.3.0
disabling djangocms-admin-style introduces other visual bugs (i'm using django-cms)

**Comment by FinalAngel** [comment]
@thelittlebug, we have not yet encountered such problems. What django CMS and Django Version are you using? Could you share your requirements file?

**Comment by thelittlebug** [comment]
sure, here is my requirements.txt file:
```
appdirs==1.4.3
argparse==1.4.0           # via djangocms-installer
astroid==2.1.0
attrs==18.2.0
beautifulsoup4==4.7.1
black==18.9b0
click==7.0
dj-database-url==0.5.0
django-appconf==1.0.2
django-classy-tags==0.8.0
django-cms==3.6.0
django-filer==1.4.4
django-formtools==2.1
django-imagekit==4.0.2
django-js-asset==1.1.0
django-mptt==0.9.1
django-ordered-model==3.1.1
django-polymorphic==2.0.3
django-sekizai==0.10.0
django-taggit==0.23.0
django-treebeard==4.3
django==2.1.5
djangocms-admin-style==1.3.0
djangocms-attributes-field==1.0.0
djangocms-bootstrap4==1.3.1
djangocms-column==1.9.0
djangocms-file==2.2.0
djangocms-googlemap==1.2.0
djangocms-icon==1.2.0
djangocms-installer==1.0.2
djangocms-link==2.3.1
djangocms-modules==0.1.0
djangocms-picture==2.1.3
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.7.0
djangocms-transfer==0.1.0
djangocms-video==2.1.1
docutils==0.14
easy-thumbnails==2.5
gevent==1.4.0
greenlet==0.4.15
gunicorn==19.9.0
html5lib==1.0.1
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pilkit==2.0
pillow==5.4.1
pip-tools==3.3.2
psycopg2-binary==2.7.7
pylint==2.2.2
pytz==2018.9
six==1.12.0
soupsieve==1.7.3
toml==0.10.0
tzlocal==1.5.1
unidecode==1.0.23
webencodings==0.5.1
wrapt==1.11.1

**Comment by thelittlebug** [comment]
some more information, maybe they are helpful.
i am using linux mint. i have disabled all browser plugins and extension. it looks differently wrong in different browsers:

vivaldi (based on webkit) 2.2.1388.37 (Stable channel) (64-bit)
![image](https://user-images.githubusercontent.com/2874956/52149693-dfd3c800-266d-11e9-84c3-812f935165a3.png)

chromium-browser Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on LinuxMint 19 (64-bit)
![image](https://user-images.githubusercontent.com/2874956/52149764-232e3680-266e-11e9-9b7c-5c00a674ea15.png)

firefox quantum 64.0
![image](https://user-images.githubusercontent.com/2874956/52149799-3e00ab00-266e-11e9-8d43-0b3a2d1a7314.png)

**Comment by cyber-dude** [comment]
+1
django==2.1.5
django-cms==3.6.0
I have same issue direct on the model admin forms, without any inlines. 
Just .form-row > div > .form-box has no any "float" properties.

**Comment by techlover10** [comment]
FWIW: I've been struggling with this issue myself, and I've finally found what I believe to be the issue.  See: https://github.com/django/django/commit/5d4d62bf4fe887fcd30f9f0449de07ae76ea5968#diff-2d163964c86d46ab97c2516908b3cdde

The issue is that Django renamed its field-box class to fieldBox, and this library didn't.  Because this library overrides everything in Django, and field-box is often used to contain all fields in a form, this breaks a lot of forms.  My solution was to override the django/contrib/admin/templates/admin/includes/fieldset.html template in my project, and change the field-box name back.  Ideally, djangocms-admin-style should be updated to be compatible with this.

**Comment by xmath279** [comment]
I also have this issue. It would be really great not to have to override a template provided by Django itself...
