### ISSUE TITLE
Replace compass against libsass

### ISSUE THREAD

**Issue by jrief** [divio/djangocms-admin-style#43]
This app would be a perfect fit to use [django-sass-processor](https://github.com/jrief/django-sass-processor) instead of compass.

@yakky remember, you asked a while ago to allow offsite compilation, so that djangocms-admin-style can be shipped with precompiled ``.css`` files, rather than having them to compile in a productive environment. Well, django-sass-processor can do that now.

If desired, I can create a PR for this. Would help during development to get rid of a Ruby dependency and having to run a directory watching process.

**Comment by lory87** [comment]
@jrief compass is replaced with libsass and will be in the new release
